version: 2
jobs:
  build:
    docker:
      - image: lineageos/docker_build
    steps:
      - run:
          name: check space
          command: df -h  
      - run:
          name: Init Repo
          command: repo init -u https://github.com/LineageOS/android.git -b cm-14.1
      - run:
          name: Sync Repo
          command: repo sync
