version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: kylemanna/aosp
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Boobs
          command: mkdir nougat ; cd nougat ; export AOSP_VOL=$PWD
      - run:
          name: get build script
          command: curl -O https://raw.githubusercontent.com/kylemanna/docker-aosp/master/tests/build-nougat.sh
      - run:
          name: get build script
          command: df -h
