version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: jfloff/lineageos
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: check space
          command: df -h  
      - run:
          name: Init Repo
          command: repo init -u https://github.com/LineageOS/android.git -b cm-14.1
      - run:
          name: Sync Repo
          command: repo sync
