version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: kylemanna/aosp
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Export working directory
          command: mkdir nougat ; cd nougat ; export AOSP_VOL=$PWD
      - run:
          name: Get build script
          command: curl -O https://raw.githubusercontent.com/kylemanna/docker-aosp/master/tests/build-nougat.sh
      - run:
          name: Init Repo
          command: repo init -u https://github.com/LineageOS/android.git -b lineage-15.1
            - run:
                name: Sync Repo
                command: repo sync
